name = "entroflow-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "eab278ebb165ac9c0ce68a68f62f785b"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "entroflow-assets"

[[d1_databases]]
binding = "DB"
database_name = "entroflow-db"
database_id = "75b05d73-2341-46a1-9e41-56e79c621cc8"

[[routes]]
pattern = "entroflow.ai/api/*"
zone_name = "entroflow.ai"

[[routes]]
pattern = "entroflow.ai/v1/*"
zone_name = "entroflow.ai"

[[routes]]
pattern = "api.entroflow.ai/*"
zone_name = "entroflow.ai"
