name = "entroflow-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "eab278ebb165ac9c0ce68a68f62f785b"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "entroflow-assets"

[[routes]]
pattern = "entroflow.ai/api/*"
zone_name = "entroflow.ai"
